### ISSUE TITLE
Dashboard crud for pull requests ( Junior Scenario + busy man )

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/code-review-pals#12]
as you see #8 we need CRUD in dashboard ( just index, create, delete, edit and redirect show to an #14  )

## technical
- make a model called PullRequest
- fields : `title`, `url`, `status`, `description`
- only `title` and `url` is fillable by user others will complete automaticly
- we will add more fields in future.
- use PHP enum for status and store string in database
- it will be good if we have simple feature test ( we need it in future )

**Comment by vassilidev** [comment]
Use the saloon request already made to get all the data needed !
