### ISSUE TITLE
github profile integration

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/code-review-pals#2]
as you know, once someone creates a new review request, should mention the Github profile.

we need an integration of GitHub API to fetch more detail of `User` by GitHub username.

what we need to get:
- is it a valid profile?
- Avatar
- name
- bio

## technical expectation
- make a service for GitHub 
- after submitting the review request ( use observer on Project model ) store data on the cache
- on show and index of Project show the sample data like (  avatar and others ) with correct data ( read from cache )

**Comment by vassilidev** [comment]
For the bio i think we need a specific call for the API

**Comment by geeksesi** [comment]
it's done, user can login with GitHub now, and we will store some data from there.
thank you @vassilidev
