### ISSUE TITLE
disable login and register with email

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/code-review-pals#34]
for now, we decided only to support login with GitHub ( in the future we can implement another git like GitLab. )

**Comment by vassilidev** [comment]
We have to delete all the Auth Files, not only disable, i dont want dead code in the codebase !

**Comment by geeksesi** [comment]
you can check this pull request to understand better what you need to change.
#11 

also if you want more information i made a video about this issue : [how to contribute on CodeReviewPals.com](https://youtu.be/l3A3JJteRfY)

**Comment by vassilidev** [comment]
Delete all Auth stuff from breeze, and views

**Comment by andreyyy178** [comment]
Assign this to me to please 🙂

**Comment by vassilidev** [comment]
Do u start something ?

**Comment by andreyyy178** [comment]
I made a pull request. Please let me know if it meets your expectations and if not, what should I have done differently. Thank you.
