### ISSUE TITLE
Handle github profiles that don't have real name filled out.

### ISSUE THREAD

**Issue by andreyyy178** [geeksesi/code-review-pals#36]
Right now we only assume that github user has a real name in their profile. Because not every github user has filled out their real name, we need to also have a column for nickname. 

Right now also if the user does not have a real name, sql will throw an error when such user is attempting to register because the column 'name' is not allowed to be nullable

**Comment by geeksesi** [comment]
Thank you, Andre,
I think we must do these steps :
- add `username`  to the user and store GitHub `nickname` as `username`
- make the `name` property on the users table optional
- if your `name` is empty show `username` instead ( do this on the model by Attribute )

**Comment by vassilidev** [comment]
I think we only need name to be the username and that's it, we'rnt a social platform.

**Comment by geeksesi** [comment]
> I think we only need name to be the username and that's it, we'rnt a social platform.

I agree with this.
