### ISSUE TITLE
review url validation

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/code-review-pals#6]
code reviews are available at GitHub/GitLab pull requests.

somehow, on submitting the review request, we should validate whether it is a pull request.

we have some options :
- do not publish the request until a human approves it.
- use URL validation ( it has a particular schema like `REPO/pull/{id}` )
- use GitHub integration to get the information of a URL ( i don't know if is it possible ?) ( also is it available for GitLab and others? )

**Comment by vassilidev** [comment]
Create a Laravel Rule with a regex

**Comment by vassilidev** [comment]
Regex exemple:  https:\/\/github\.com\/+([A-Za-z-]+)\/+([A-Za-z-]+)\/pull\/+([0-9]+)
