### ISSUE TITLE
extract information of request

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/code-review-pals#7]
main document #8 

please see #15 and #9 

this website could be a hub to connect open-source contributors and project owners.

for a better experience, we should display more information about a request.

likes : 
- pull request status
- project languages
- description of the pull request
- project details, stars, ...

## technical 
- [ ] each pull request should check status in period
- [ ] we should add more fields on PullRequest model ( based on what data we can extract )
- [ ] we should talk about update status strategy
- [ ] make a service to get detail of a pull request also check #15 
- [ ] write strong test please

**Comment by abbasudo** [comment]
for now, i will implement these features only for GitHub. other platforms will follow up when we finish mvp state.

GitHub has a well-documented api that we can use to extract the data that we want.
The good news is Github supports [webhook](https://docs.github.com/en/rest/webhooks/repos?apiVersion=2022-11-28#create-a-repository-webhook) for updates so we don't have to make a corn job or any complex solutions to get status updates.
