### ISSUE TITLE
Crud for Repositories ( Busy man scenario )

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/code-review-pals#9]
as you can see on #8 we need a form for a busy man to submit their project.

then he can manage them on his dashboard:
- [x] manage repositories
- [x] manage pull requests ( we can do nothing for this because it's the same as making a manual review request #12  ) 

## technical 
- have a model called `Repo` ( do not name it Repository because conflicts naming with the Repository pattern )
- use soft delete for deletion
- do this on user dashboard.
- for now just store it and do nothing. :)
- it will be awesome if we have some test for the crud. ( simple one )

**Comment by vassilidev** [comment]
Fetch repo from username with "get user repo list" saloon request

**Comment by geeksesi** [comment]
thank you Vasili it's done
